QW-Group/ezquake-source

Makefile
...make sure we can relink dynamic libraries.
=> osx compile fixes

host.c
=> Fix f_system on Mac OS X

cl_main.c, cl_parse.c, cl_tent.c, client.h, rulesets.c
This reverts commit a6870fdec9a82e42402ce112a660b68511dc456a.
After playing online with this, there are too many issues with tracking
the current user's weapon in certain situations, and also with correctly
filtering the blood from the server (the network protocol doesn't tell us
what beam caused the damage or by who, so we go by distance, which doesn't
work when the enemy target is moving quickly, including when we are
pushing them back) that the actual results aren't good enough yet.
A lot more thought needs to go into it before it is ready for public
consumption.  Reverting for the moment, will look at again in the future.
=> Revert "cl_fakeshaft 3"

cl_main.c, client.h, menu_options.c, sv_user.c, teamplay.c, vx_tracker.c
Gender cvar reflected & added to menu options.
Fixed-length location name change from yesterday affected more than just teamplay macros, so changed function back to how it was and altering at macro-function level instead.
=> Gender cvar, and fix for fixed-length location name change.

Makefile, misc/install/create_osx_bundle.sh, sys_osx.m, sys_posix.c
Yeah well.. pretty much thrown into here. No idea if `Cbuf_AddText()` is the correct way to trigger a new qwurl? And of course that ugly `#ifdef __APPLE__` in `sys_posix.c`.. well feel free to move things around. Most important to note is however that it seems to be working.
=> add qw:// protocol for OS X

Makefile, cl_main.c, help.c, help.h, help_commands.json, help_variables.json
.json file embedded in executable, loaded on startup.
=> JSONHELP: Convert xml documentation to json

cl_screen.c, hud_editor.c, in_sdl2.c, vid.h, vid_sdl2.c
Hifi's changes + keeping internal Quake cursor for most modes, even when windowed.
(needs second opinion)
=> Fix cursor tracking in menus & windowed mode.

EX_browser_sources.c
Bug report from The Beats.  This fix just ignores extra servers at the
moment and reports number of servers ignored to the console.
=> Prevent buffer over-run when using > 1000 sources in demo browser.

demo_controls.c
Don't allow demo_controls to be switched on if not playing demo.
Disable demo_controls if not playing demo.
Stop button returns control to console.
Extra space for speed % label.
Primary concern was bug that currently you can enable demo_controls when playing a game, then use the slider - entities will stop animating, new entities (outside the current vis region, or rockets etc) will not appear, and the player will not have angles set when teleporting.
=> Minor fixes for demo_controls, found during mouse cursor changes.

hud_common.c, teamplay.c, teamplay.h, utils.c, utils.h
For demo playback only, allow titles for twitch streams etc.
Multiple lines available via $\, alignment/spacing calculated per line.
=> HUD: Add static text hud element

menu_options.c, vx_tracker.c
Tracker expected "female" or "1" from server, set "1" in menu.  KTX demands "f" or "m", so set that instead (can't find other mods/clients with a standard, so just make compatible with KTX)
=> GENDER: Change userinfo values to be ktx-compatible

.gitignore, .travis.yml
Now you can enable travis-ci.org integration.
=> Add Travis CI config file

.travis.yml
=> Add windows cross compilation to Travis config

help.c, help_variables.json, xsd_variable.c, xsd_variable.h
Fix error made during import where some enums were converted to strings.
If type is missing, no longer reports "boolean value" (reported by Ch0wW)
Tried to add some more descriptions/types to missing variables
Added /help_issues command to list errors in documentation.
=> HELP: Correcting errors & adding missing data

EX_browser.c, EX_browser.h, EX_browser_net.c, EX_browser_sources.c, cl_demo.c, cl_ents.c, cl_main.c, cl_parse.c, cl_pred.c, cl_screen.c, client.h, movie.c, movie.h, snd_main.c, snd_mix.c, sys_sdl2.c, vid.h
Fix audio synchronisation bug in .avi generation (windows only)
Hide names and chat icons during intermission (affects screenshots)
QWD playback should be smoother
Initial patches for common server browser threading issues
Server browser code was from March, but I'd fixed a bug dimman pointed out and then completely forgotten to re-upload.
=> Various bug fixes

COMPILING_ON_OSX.txt
[BLooD_DoG commented this](http://www.quakeworld.nu/forum/topic/6918/page/last#104550), and I just confirmed it on 15F34.
=> OSX: Update library dependency list for OSX (pkg-config)

fs.c
Fixes ezQuake/ezquake-source#152.
=> Fixes ezQuake/ezquake-source#152.

ez_listview.c, ez_listview.h, ez_listviewitem.c
Just removed some unused code that caused compiler warnings. I guess there is no need to keep them when they don't do anything?
=> Remove some dead code

EX_browser_sources.c
This brings back reverted PR with properly set email. @meag thnx
=> SERVERBROWSER: Fix OSX issue with URL sources. Refactor of source load

build-linux.sh
Updated linux build script to run without root privileges, instead use sudo with relevent commands.
=> BUILD: Updated linux build script to run without root privileges

cl_parse.c, cl_screen.c, common.c, fs.c, mp3_winamp.c, progs.h, sv_ccmds.c, sv_demo_misc.c, sv_user.c
Easy one line fix for #311 
and some other minor fixes
=> Fixing compilation without USE_PR2

EX_qtvlist.c
Even if we do not plan for a release anytime soon - the nightly builds can still pick this up.
=> QTV: update api url

.travis.yml
I updated the travis file to support the latest version of macOS as well as the previous xcode version on 10.12.
=> Support latest macOS in travis CI

build-linux.sh
=> SNAFU: Fix Linux build script

mvd_utils.c
Fixed a small bug with the new hud_itemclocks (style 6 and 7) y spacing
=> Fixed a small bug with the new hud_itemclocks (style 6 and 7) y spacing

COMPILING_ON_LINUX.txt, build-linux.sh, cl_main.c, utils.c
LINUX: updated fedora dependencies
NET: set default rate to 25000
IGNORE: allow the use of regular expressions in ignore
=> LINUX, NET, IGNORE

in_osx.c
Simplfy a few parts. Gracefully handle unsuccesful opening of
the input manager. 'Input Monitoring' permissions must be given
to the the process in order to use raw input. Also wait for the
input thread to start/fail before returning main init function.
That should avoid the potential race condition we had lingering
there for quite some time.
=> INPUT: macOS in_raw, refactor input code

Makefile, README.md, image.c, misc/install/create_osx_bundle.sh
Added a missing brew package and forced some libraries that were not being detected to use `pkg-config`
=> Small fixes for the M1 build

EX_browser.c, cl_screen.c
allow serverinfo help/extended information box to be displayed at higher conscales/lower resolutions
=> Server browser Serverinfo help dialog

Makefile, cl_demo.c, ezQuake.vcxproj, ezQuake.vcxproj.filters, meson.build, sha3.c, sha3.h
Support for client only, server should be synced with mvdsv separately.
=> AUTHENTICATION: qtv support SHA3-512 auth method

r_brushmodel_load.c
=> SKY: apply gl_scaleskytextures to external textures

glc_local.h, glm_local.h, sys_osx.m
Just two small things I came across while giving the latest code and latest macOS things run.
=> Compile fixes (for macOS)

COMPILING_ON_LINUX_DOCKER.txt, Dockerfile.focal-cross, HOW_TO_BUILD_WINDOWS_ON_LINUX_using_Dockerfile.txt
That was easier than I expected.
=> Add description how to build Windows binary under Linux in Docker

hud_teaminfo.c
=> HUD: Fix text powerup width calculation.

EX_qtvlist.c
Works much like the find command, except instead of printing the
server address and port, it connects directly to the server.
=> ADD: 'follow' command to find a player by name and connect to the same server

cl_main.c, client.h, qsound.h, r_refrag.c, render.h, sys_posix.c, sys_win.c
This fixes various parts of #665 and loads the new rctf maps correctly.
=> LIMITS: Bump limits to allow loading modern maps.

.config_windows, .config_windows-clang, Makefile
BUILD - update windows config files for building via mingw to overcome some 32 bit issues
=> Windows mingw config update

gl_model.h, glm_rsurf.c, glsl/constants.glsl, glsl/draw_world.fragment.glsl, r_brushmodel.c, r_brushmodel_load.c, r_lightmaps.c
=> BSP, MODERN: Add support for lit water.

src/r_brushmodel_load.c
The lack of precision frequently caused black artifacts on the map. The workaround used to be adjusting texture scale in the map ever so slightly.
Originally fixed in Quakespasm:
https://github.com/sezero/quakespasm/commit/bfab14040b2f65e02572960f8dc4b1b346f8c151
Fixes #741
=> BSP: Fix rounding error in CalcSurfaceExtents.

src/cl_view.c
=> fix punchangle staying at ideal_punchangle value

help_commands.json, src/keys.c
=> Add bindedit command

help_variables.json, src/vx_tracker.c
fix for #715 and add a cvar for enemy vs enemy kill color (`r_tracker_positive_enemy_vs_enemy`)
=> fix for #715

src/r_brushmodel_load.c
Saves a couple of MB by removing redundant lightmaps.
=> BSP: Load bspx lighting for maps compiled with -novanilla.

help_variables.json, src/cl_tent.c
requested on the quakeworld discord [here](https://discord.com/channels/166866762787192833/179895022366228481/1134763771374604350)
=> add r_sgbloodColor

src/hud_clock.c
=> make hud_scoreclock on by default

help_commands.json
Also updated connectbr description.
=> Updated help_commands.json with new command observebr

help_commands.json, src/cmd.c
=> copy to clipboard command

src/sv_send.c
=> trigger_secrets now play their sound at the proper location

help_variables.json, src/vid_sdl2.c
=> modern defaults for gamma settings

misc/install/fixbundle.sh
=> INSTALL: Include all of libsndfile's dependencies.

.github/workflows/scripts/homebrew.sh, misc/install/create_osx_bundle.sh
* Missed one dependency.
* Launcher script built invalid executable path.
* Launcher script now supports arguments.
=> MACOS: Fix remaining issues with .app bundle.

.github/workflows/scripts/homebrew.sh, Makefile, README.md, build-linux.sh, ezQuake.vcxproj, src/EX_browser.c, src/cmd.c, src/fonts.c, src/parser.c, src/parser.h, src/sv_demo_misc.c, src/sv_mod_frags.c, src/sv_sys_win.c, src/sys_posix.c, src/sys_win.c, src/teamplay.h, src/tp_triggers.c, src/tp_triggers.h, src/utils.c, vcpkg.json
Here is my quick attempt to move to PCRE2.
It did compile on Linux and macOS. Windows changes were made blind, so I guess there some things that I have missed.
Just did quick test whether the sample regex scripting example still works and it did. I'm pretty sure there are some bugs in there. So I guess it needs quite a big of testing.. so step forward..
Windows will need updating of the pre-compiled lib and header files.
=> PCRE -> PCRE2

help_variables.json, src/cl_tent.c
```
r_rlbloodcolor_small
r_rlbloodcolor_big
```
These work like r_lgbloodcolor.
=> New variables for rocket explosion blood color

help_variables.json, src/gl_program.c, src/glm_rmain.c, src/glsl/fx_world_geometry.fragment.glsl, src/r_program.h, src/r_rmain.c
https://discord.com/channels/166866762787192833/709360526899150858/1175074808749379665
=> gl_outline_world_normal_threshold

cmake/AddResources.cmake, help_commands.json
If jq exists fail if json files to be embedded contain syntax errors.
=> CMAKE: JSON validation and fixup.

.github/workflows/build-and-deploy-release.yml, .github/workflows/build-and-deploy-snapshots.yml, .github/workflows/build-targets.yml
=> CI: Switch Windows builds to msvc.

help_variables.json, src/glm_framebuffer.c, src/glm_local.h, src/glm_misc.c, src/glsl/common.glsl, src/glsl/post_process_screen.fragment.glsl, src/menu_options.c, src/vid_sdl2.c
Default disabled, ideally used with vid_framebuffer 2 to avoid adding AA to HUD.
NVIDIA FXAA Shader v3.11, BSD license, imported verbatim.
=> RENDERER: Add FXAA option.

help_variables.json, src/cl_screen.c
Setting showturtle to 70 will make the turtle appear when the FPS drops to 70 or below.
=> Resurrect the turtle

src/cl_main.c, src/rulesets.c
The userinfo string will look something like this:
```
...\*ver\ezQuake v3.6.6-dev 7927~cf8de3304\*rsn\smackdown\...
```
=> Add more userinfo

help_variables.json
- Swaps descriptions 1/2 to match the actual code
- Add undocumented option 4
=> HELP: scr_teaminfo_armor_type tweaks

help_commands.json, help_variables.json
Resync json from code (housekeeping!), then some touch-ups.
Warning - as usual this re-sorts everything, some blocks get moved around.
Lengthy (but not fully complete) list of adjustments in the commits.
=> HELP: Summer clean-up
