- misc/install/create_osx_bundle.sh
bugfix: in case of when the app bundle is installed in paths with whitespace in them it would fail. this patch hopefully escapes them correctly.
> bugfix for os x bundle: properly handle whitespaces

- vid_sdl2.c
- fix low resolution icon os osx
- fix other osx window/mouse issues (hopefully)
Potential fix for issue #32 
Alt-Tab acts differently works around some display issue
Icon now looks nice
> OS X fixes for logo and window/mouse behavior

- cl_cam.c
- cl_demo.c
- cl_ents.c
- cl_main.c
- cl_nqdemo.c
- cl_parse.c
- cl_view.c
- client.h
- com_msg.c
- in_sdl2.c
- movie.c
- movie.h
- sbar.c
- settings.h
- settings_page.c
- snd_dma.c
- snd_mix.c
Mostly changes to let me watch/re-record old demos
NQ demos: player colours set correctly, particle trails/effects back in, demo_jump working, can force team skins with help of cl_demoteamplay
QW demos: can now playback from 2.1 (protocol versions 24/25), demo rewinding works
MV demos: cam_pos stops tracking, if in free camera mode, camera position is restored after rewinding
Video capture: Can split .avi files to be stitched together later (workaround for http://sourceforge.net/p/ezquake/bugs/520/), demo_capture_quiet option to disable playback during capture.
Demo browser: plays the file you select when you have two files with valid demo extensions in same directory
> Changes related to demo playback

- cl_demo.c
- cl_screen.c
- client.h
- console.c
- hud_common.c
- menu_ingame.c
- movie.c
- qtv.c
- qtv.h
- vx_coronas.c
Particle effects & sounds were paused, but entity movement unaffected.
It was possible previously to pause QTV playback and then start again (as long as qtv_adjustbuffers was set to 0) - if this is still required, can set qtv_allow_pause to 1.  Hopefully the new default causes less confusion.
> Fixes for cl_demospeed 0 affecting QTV playback

- cl_parse.c
- teamplay.c
- teamplay.h
If teamlock is set, the current tracked player may not be a teammate.  Existing code always considers the tracked player a teammate, so +showscores looks confusing when using teamcolor/enemycolor settings.
Example of bugged +showscores here:
> Bugfix for teamlock setting

- misc/docker-nightly-build/Dockerfile
- misc/docker-nightly-build/README.md
- misc/docker-nightly-build/build_image.sh
- misc/docker-nightly-build/forcebuild.sh
- misc/docker-nightly-build/image_outputdir
- misc/docker-nightly-build/linux.sh
- misc/docker-nightly-build/mk_nightly.sh
- misc/docker-nightly-build/nightly.sh
Scripts and Dockerfile to build windows and linux versions of ezquake. Used to create nightly builds.
> Docker nightly build

- cl_main.c
- cl_parse.c
- cl_tent.c
- client.h
- cmd.c
- config_manager.c
- console.c
- draw.h
- gl_draw.c
- in_sdl2.c
- keys.c
- keys.h
- menu.c
- rulesets.c
- teamplay.c
- textencoding.c
- vid_sdl2.c
This will need a reasonable amount of testing by people with varying configurations.
- Extra cvars to choose which display to use (vid_displayNumber / vid_win_displayNumber).
- Support for keyboard layouts - in SDL2 this means picking up the TextInput event, as the unicode character(s) don't get passed with key up/down.  Have done some testing of other layouts, generating cyrillic characters, euro symbols etc.  See below for change to bind command.
- Cyrillic characters - now support various encoding methods for unicode for outgoing characters (cl_textencoding cvar), but default is 2.2's k8 encoding (more work to be done for utf8 generally)
- Character sets can now cover the 3-byte range of utf8 values (0-0xFFFF), if initial charset is called XXX then system will attempt to load XXX-yyy …
> Multi-monitors, non-american keyboard layouts, cyrillic characters & a fakeshaft experiment

- misc/docker-nightly-build/Dockerfile
- misc/docker-nightly-build/README.md
- misc/docker-nightly-build/forcebuild.sh
- misc/docker-nightly-build/linux.sh
- misc/docker-nightly-build/mk_nightly.sh
- misc/docker-nightly-build/nightly.sh
Updated the **Dockerfile** to 
* Include the jpeg-lib for linux builds (also updated the mingw32 archive to include this lib, which resolves issue #50 )
* Add a /source-volume to keep the source in, instead of letting them reset to the time the image was created on every run.
* Removed tab-indentation to appease the wrath of @JoakimSoderberg 
**mk_nightly.sh**
Use /source instead of container-local storage. Initialize the repository if needed.
Use the same script to build for both linux and windows builds.
Updated helper scripts and README.md reflect these changes
> Fixes for the nightly build scripts.

- Makefile
Actually homebrew puts every lib in its own directory. So existing include paths won't help us for jpeg. Since there is no .pc file for pkg-config we need to handle this ourselves. Explicitly add `/usr/local/include` as 10.11 removed this path from its default search paths.
> fix jpeg for OS X 10.11

- misc/docker-nightly-build/Dockerfile
- misc/docker-nightly-build/README.md
- misc/docker-nightly-build/build_image.sh
Now that the mingw32-libs are in the repository we don't need to download them when building the image
> Don't download mingw32-libs from external source

- keys.c
Key_ClearStates is called during vid_refresh, this makes sure any keys held down at the time bound to +alias fire appropriate -alias event.
> KEYS_C: Let -action events fire when clearing key states.

- cl_demo.c
- cl_parse.c
- config_manager.c
- hud_common.c
score_bar changes are response to request from andeh, so he can get hud to keep scores in same position as point of view changes (example https://www.youtube.com/watch?v=3mJDh8NNSsQ)
qtv_fixuser allows user to directly set name/team/colour of users when viewing a QTV stream (commonly-deployed version of QTV has bug that can corrupt userinfo strings)
Muzzle flashes - during MVD playback, client was creating dynamic lights for muzzle flashes several (sometimes 63 by end of demo) frames behind the current frame.  (example at https://www.youtube.com/watch?v=GlFJWXR2jdM)
> Various small fixes & qtv_fixuser command

- client.h
- gl_rpart.c
- hud_common.c
- menu_mp3player.c
- movie.c
- mp3_winamp.c
- sv_main.c
- sys.h
- teamplay.c
- teamplay.h
- tr_types.h
- utils.c
- vid_sdl2.c
Removed references to unused variables, initialised some that weren't set in all paths
Removed some unused console variables
Bugfix for recent score_bar change (.qwd playback affected)
Teamplay: fix for tp_took when item pickup sound arrives before stat update
Teamplay: took & point timeouts are variable, instead of fixed 15s
Teamplay: location descriptions can be fixed width
> Teamplay updates for pickup detection & location reporting, compiler warning fixes

- help_variables.json
Change groups section to have id & major grouping, for external docs.
Added group-id field to each cvar (taken from dump_defaults comment)
Corrected spelling of that word.
> HELP: Link cvars to groups

- misc/install/create_osx_bundle.sh
- vid_sdl2.c
These changes add .mvd file support to OS X. You double click a .mvd file from the finder and the app launches and plays the demo. Or if it is already launched it will play the demo that has been clicked. You can also drag and drop the file onto the app's icon of course.
> .mvd support for OS X

- Makefile
Build ezquake to run on OS X 10.8 or later. This will be helpful when creating official releases or something. Note however that to make this work correctly the dependencies must be compiled with this support restriction as well (jansson/jpeg/pcre/png/sdl2).
This change should be safe. If the dependencies are not build for 10.8 it will still work as long as the target machine meets the requirements of the highest used library.
> osx: target OS X 10.8 as minimum requirement (without deps)

- help_variables.json
- vid_sdl2.c
Connection status doesn't affect cursor handling
New cvar in_release_mouse_modes, allows user to determine when cursor is released back to operating system
> VID_SDL2: tweaks to SDL2/OS mouse cursor

- console.c
- snd_dma.c
- tp_msgs.c
tp_msgutake was displaying %l instead of location when pointing at teammate
s_desiredsamples is now a latch cvar, and user can check actual number of samples (autoset)
hud_notify was using con_notifylines cvar instead of hud_notify_rows (reported by Milton)
> Small fixes

- cl_main.c
- client.h
A number of variables need to be set to sensible values during multiview
playback.  If not in multiview, the old values are saved, and then restored
before initiating a new connection.  If the command line caused an
immediate connection, the values would be set to their default values,
ignoring options that the user has set in their config file.
> MULTIVIEW: Don't reset variables on initial startup

- misc/install/create_osx_bundle.sh
allow start up with pak0.pak installed only. This may be useful for nQuake like installs which install just pak0.pak from shareware version of Quake.
> osx: allow start up with pak0.pak only

- common_draw.c
- common_draw.h
- gl_draw.c
- gl_texture.c
- host.c
- hud_common.c
- q_shared.c
* Reuse same code for all groups
* Fix the log spamming bug
* Introduce CachePic_Remove and reference counting. Not used atm for the
hud_group pics because with the current code it's not possible to
determine which pic to unload. First attempt used the old cvar-value,
however that turns out to be a bad idea during a vid_restart. Code is
there and can be used in the future if there's a way to determine
which picture to unload (or decrease refcount on).
* Change CachePic_Add function to make it responsible for data copying
instead of letting this be up to the caller. Makes it possible to skip
adding a picture that's already in there.
* Add a warning message to Com_HashKey function in case it's called with
NULL argument. Basically a developer helper, could have been an
assert() but IMO …
> HUD_GROUPS: Fixup hud group code a bit

- EX_browser.c
Fixes ezquake/issue#102.
In  the server-browser failed search strings are not shown so the user is left guessing as to why no servers are showing. Now failed searches will be displayed on the bottom of the screen.
> Serverbrowser: Print searchstring on search failure.

- misc/install/fixbundle.sh
There is no point in parsing Info.plist. In our case the executable is a shell script and no binary. Newer Xcode versions throw and error here.
> fix fixbundle.sh

- help_variables.json
`cl_clock 1` - it's no longer displayed in status bar when pressing TAB.
`hud_score_bar_fixed_order 1` https://github.com/ezQuake/ezquake-source/issues/184 >> %t should be the current point of view, not the leading team - is this not happening? - @meag
`hud_frags_style 3` - similar to 1? more like 0
`hud_teamfrags_style 3` - same as above
`scr_compactHud 4` doesn't seem to show compact hud with weapon's ammo in big numbers anymore
And that all what I remember.
> Edit some cvars infos (/describe)

- cl_cmd.c
- gl_rsurf.c
- sv_login.c
- sv_user.c
- teamplay.c
It may have been that these were pointers before - but now are character arrays. So better check if the first character is set instead of checking whether the memory address of the character arrays is non-NULL.
> ALL: fix checks for if-a-string-is-set

- EX_browser_net.c
Not sure if all platforms include the `uintptr_t` type currently. Works for me..
> EX_BROWSER_NET: silence compiler about void* <- int casting

- Makefile
fixes missing symbol sched_yield from libjansson
mingw32-libs/lib/libjansson.a(hashtable_seed.o):(.text+0x41): undefined reference to `sched_yield'
> add pthread on windows

- meson.build
- xxd.sh
Alternative way to build ezquake.
Cross compiles probably not covered as it is expected the build machines provides libraries that are being linked. So mingw build does not make use of the ezquake's provided mingw library versions.
Builds for:
- Linux
- macOS
- Windows from MSYS2
It has been a while I looked at CMake - but mesonbuild felt immediately more fun.
P.S. Not sure if I caught all of the funky secret #defines and source files though..
> add experimental meson build system file

- q_shared.h
I think these things are due to Visual Studio being Visual Studio. When compiling on MinGW these should not be needed. And in fact the compiler spills a lot of warnings:
```
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/guiddef.h:149:0,
from C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:628,
from C:/msys64/mingw64/x86_64-w64-mingw32/include/minwindef.h:163,
from C:/msys64/mingw64/x86_64-w64-mingw32/include/windef.h:8,
from C:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:69,
from C:/msys64/mingw64/x86_64-w64-mingw32/include/winsock2.h:23,
from ../common.h:32,
from ../zone.c:25:
C:/msys64/mingw64/x86_64-w64-mingw32/include/string.h:120:0: note: this is the location of the previous definition
#define strcasecmp _stricmp
```
So I think we are better of …
> Q_SHARED: do not redefine strcasecmp() and strncasecmp()

- help_variables.json
- menu.c
- vid_sdl2.c
As I have a 21:9 monitor, the menu is way too stretched.
Before:
After:
I also took portrait aspect ratio into consideration, so the menu will still look good if the height is bigger than the width.
I am not sure about vid.aspect, it is defined in vid.h viddef_t. But as far as I can see never actually set.
scr_scaleMenu is now the scale factor of the menu.
> Mainmenu aspect ratio

- common.c
- fs.c
The functions "COM_GetUniqueTempFilename" and "COM_GetTempDir" contained
inconsistent handling of return values in some error cases (errors were
being masked).
I noted that error handling strategy varies throughout the code but I opted for zero on failure as that was how the functions were being used.
> Fix return value inconsistencies for temp files.

- meson.build
We just assume any OS which is not explicitly checked for is roughly POSIX compliant and has X11.
The alternative would be explicitly listing and checking all supported Unix system.
``` meson
elif ['dragonflybsd', 'freebsd', 'linux', 'netbsd', 'openbsd'].contains(host_machine.system())
```
This could get quite long. For example, despite what the [documentation](http://mesonbuild.com/Reference-manual.html#build_machine-object) says, the value of `host_machine.system()` on FreeBSD is not `bsd`, but `freebsd`.
> Make Meson work under any POSIX+X11 OS

- EX_browser_sources.c
- Fixes issue on a Mac where servers are not refreshed properly after updating sources.
- Reworked SB_Update_Source_From_URL. It doesn’t rely on file creation to update servers - so now it will also work on read-only media.
- Refactored SB_Update_Source_From_URL into more focused funcs.
- Additional error checking.
- Tested on a Mac Book Pro
- Would be good to test on a Windows / Linux machine ;)
> Fixed server loading on a Mac + small refactor of source loading src

- EX_browser_sources.c
Reverts ezQuake/ezquake-source#249. This is to revert commits with wrong email, and then commit back with the right one.
/cc @meag
> Revert "Fixed server loading on a Mac + small refactor of source loading src"

- meson.build
Found that in the change-log for 3.1. Better add this to meson too to avoid nasty surprises.
> meson: add '-msse2' option when available. apparently we do that for accuracy

- meson.build
If system installed minizip library is found we build and link
using that one. Else we will add our ouwn minizip source files.
> MESON: catch up with minizip changes

- misc/install/create_osx_bundle.sh
Changes how the Finder is invoked when no .pak files are found.
Fixes #312
> MACOS: fix bundle creation

- hud_teaminfo.c
Going from 3.1 to 3.2, the hud_teaminfo team header started aligning the ". frags" text to the right of the teaminfo element.
In the merge to 3.6 the result was broken when this was switched to *Draw_SStringAligned* :
* *y* argument broken, not using the incrementing version : headers overlapping on one line,
* scaling and alpha arguments flipped,
* width, referring to width of the hud element in most other uses of *Draw_SStringAligned*, was overloaded by a new definition in the loop, breaking *text_align_right*.
> TEAMINFO : fix right-aligned frags in header from 3.2->3.6

- help_variables.json
- menu_options.c
- settings_page.c
* A bunch of float menu items seem to have double digit precision, but the sliders only use one digit. This enables finer grained control from there as defined per those settings.
* r_fullbrightskins and r_rocketlight do work as floats, but are not documented as such. This exposes the functionality from the menu (help_variables.json not adjusted to reflect this yet) instead of having them as simply booleans.
> MENU : double digit precision for float vars, fbskins/rocketlight adjustable as floats

- misc/docker-nightly-build/Dockerfile
- misc/docker-nightly-build/README.md
- misc/docker-nightly-build/forcebuild.sh
- misc/docker-nightly-build/linux.sh
- misc/docker-nightly-build/mk_nightly.sh
- misc/docker-nightly-build/nightly.sh
The Arch Linux repository on Docker Hub has moved, but the Dockerfile didn't build anymore with any of the new tags. Since I'm not familiar with Arch Linux, I switched the build environment to Debian Buster and fixed up the Dockerfile and accompanying scripts.
> Fix the Docker image of the nightly build

- help_variables.json
- sbar.c
Defaults to `1` to not change existing behavior.
`/scr_sbar_drawarmor666 1` (default) with pent:
`/scr_sbar_drawarmor666 0` with pent:
> HUD: Add /scr_sbar_drawarmor666 to be like /hud_armor_pent_666 for old hud

- help_variables.json
The letter for ring appears to be E (i guess for eyes) and not R (that's already used by red armor)
> fixed gamesummary help text for Ring

- hud_ammo.c
- hud_armor.c
- hud_face.c
- hud_guns.c
- hud_health.c
- hud_items.c
In newhud, going freefloat keeps the last tracked player's inventory on the screen, disconnected from its actual state.
This change makes it behave as per oldhud (and other Quakes etc) where going freefloat does not show the last player's inventory.
> NEWHUD : skip player inventory items when freefloating

- host.c
rdtsc is available only on Intel architectures. PPC64's equivalent is Time Base Register, which this patch implements.
BTW, support for FreeBSD seems awfully outdated. FreeBSD 4.x has been unsupported for 13 years, so you could use `sysctl hw.clockrate` just fine, but probably only on Intel architectures (it's definitely not supported on powerpc64).
> Fix build on FreeBSD/powerpc64

- .travis.yml
Installing dependencies will pull in a newer version of python3.9.
For some reason installing over an existing installation fails
miserably. Removing it prior seems fine.
> TRAVIS: macOS, remove python3.9 before installing deps

- misc/install/create_osx_bundle.sh
- misc/install/fixbundle.sh
- change bundle identifier to ezquake.github.io (fixes #294)
- add a sensible version string taken from version.h to the bundle
- move the base dir to $HOME/Library/Application Support/ezQuake (data files outside bundle on a per user basis, for convenient update, secure bundle stuff, when downloading?)
- check deps being in 'homebrew' folder, newer versions seem to have changed locations
Note that packaging invalidates signatures of dylibs, so we need to figure out how to re-sign.
> MACOS: fix/change/refactor application bundle

- hud_radar.c
- image.h
Since we have `WITH_PNG` scattered around the code it seems to be an optional feature. With these changes the client can actually be compiled when the feature is not present or disabled.
> BUILD: Fix some WITH_PNG guards to allow build without PNG enabled

- misc/install/fixbundle.sh
ARM builds will require a codesign - period. So we remove the
exisiting signature coming from brew.sh and add some addhoc
signature after install_name_tool is run. It may not pass
Gatekepper, but if one disables Gatekeeper locally you actually
have a chance to correctly run it.
--
With these changes I was actually able to create a M1 bundle that runs.
> MACOS: codesign changes for bundle creation

- misc/install/create_osx_bundle.sh
Allows to play these demos by double clicking the demo files.
This is a left over from #294.
> MACOS: Add .qwd and .dem as supported demo types

- misc/install/create_osx_bundle.sh
Some improvement over d2197717a432c56f1ce0302e30c608061f1e51d9
It does the same, but it does not need to be that verbose as it was.
> MACOS: simplify macOS bundle demo file associations

- help_commands.json
- help_variables.json
A bunch of tidying & consolidation of the formatting of what is already there in commands+variables, before I tackle describing more stuff that only has placeholders, or even doing large scale rewording.
- removed over-escaped backslashes, extraneous whitespace
- removed most excessive linebreaks - there were plenty from an era where I assume the console wasn't word-wrapped as well, but with the variable console line length, they end up creating some broken random whitespace depending on settings. Since there's still quite the WALLS of text, some extra linebreaks (*actual* newlines) have been placed to keep some "air" in the text blocks
- streamlined some wording, fixed some broken english
- consistent formatting of lists within cvar/cmd descriptions (not individual value descriptions)
- …
> HELP: third batch of updates

- hud_teaminfo.c
Add a switch to make headers (team name **.** score) optional on hud_teaminfo (to make it look like scr_teaminfo if you prefer to save some screen space).
> HUD: make hud_teaminfo headers optional

- COMPILING_ON_LINUX_DOCKER.txt
- Dockerfile.focal
Add basic Dockerfile for Ubuntu Focal
Add basic .txt file how to compile under Linux with Docker.
Signed-off-by: Michał Sochoń <kaszpir@gmail.com>
Partially solves #545 - I was able to compile binary for my platform in about 5 minutes :D
> Add basic howto build Ubuntu 20.04 build in Docker

- help.c
- menu_options.c
- changed gamma range to match actual var
- added gl_modulate
- reformatted variable description pop-up to closer match /describe format: section order, section headers, coloring and list separators
- some grammar along the way (value/values)
> MENU: tweak/add 2 vars, reformat var description pop-up

- host.c
While the code was fixed for powerpc64 (and powerpc64le), it still fails to build on powerpc (32-bit). Since it's possible to use the same way on 32-bits, do it to fix build.
It may fail on the early powerpc chips, but I doubt they are able to run a modern OS with OpenGL anyway.
> Fix build on FreeBSD/powerpc

- hud_frags.c
In "powerbar" styles, players displayed flipped with hud_frags_fliptext did not have a background on their armour bar.
> HUD: missing BG on "powerbar" hud_frags when flipped

- help_variables.json
Summary:
- some group-id set on obsolete things in the vid_ section.
- rewrote some vid_ vars
- wrote vid_framebuffer_\* descriptions from looking at the code and some opengl reference
- scr_autoid\* reworking
- tweaked/rewrote some sound-related vars
A question snuck in there for vid_colorbits: does this work at all? the only matches are in the menu, it says 16/32 while the var  does not change follwing the menu (and its description says 24b). Either way, I can't see any difference between any options and vid_gfxinfo assures me we're still in 24 (in either classic/modern).
> HELP: new batch of variable descriptions

- help_variables.json
Found by dracs.
The behaviour is 0 = not borderless, 1 = borderless
The help says 0 = borderless, 1 = not borderless
This commit at least flips it around.
IMHO should become scr_scoreboard_border with 0 = no border, 1 = border and `if border, draw_stuff` in sbar.c but twisting the wording around means 0 config changes.
I didn't want to keep "controls behaviour" in main desc. because it's really on/off, not style1/2/3/4, wasn't sure about saying "toggles" either because I expect 0 to be off and 1 to be on...
> HELP: Make scr_scoreboard_borderless desc. logical

- misc/install/fixbundle.sh
Fixes #624.
Maybe wait for confirmation in #624, but it seems to make more sensible install_name_tool rewrites than before.
> MACOS: fix fixbundle.sh due to latest macOS toolchain breakage

- help_variables.json
A *bunch* of rewriting old stuff, covering missing old and new stuff and various cleanups like purging redundant "1 is on, 0 is off"...
- gl_bounceparticles: moved from value to main description, pruned on/off values
- gl_buildingsparks: typo
- gl_clear: reworked, pruned on/off values
- gl_caustics: simplified, pruned on/off values
- gl_colorlights: reworked, pruned on/off values
- gl_clipparticles: reworked, pruned on/off values
- gl_detail: rewrote description, pruned on/off values
- gl_ext_texture_compression: rewrote, pruned on/off values
- gl_externalTextures_bmodels/world: rewrote description
- gl_finish: pruned on/off
- gl_fog: removed "gl only"
- gl_consolefont: reworked, split into desc/remarks
- gl_fb_bmodels/models: flipped description from values to main desc. pruned on/off …
> HELP: the "gl_variables" episode

- help_variables.json
- hud_armor.c
- hud_frags.c
> SBAR: Avoid GA overflow when carrying regeneration rune.

- fmod.c
Implements request by @ginzberg
see: https://github.com/ezQuake/ezquake-source/issues/582
Add SHA1 checksums for the Quake re-release sounds that f_modified cares
about. f_modified checks now pass with a modified pak0.pak that uses
sound/ from the Quake re-release.
While here, fix sound category for sound_weapons_mindgrid_plyrjmp8 -->
sound_player_mindgrid_plyrjmp8.
> Allow for the Quake re-release sound files to pass f_modified checks

- cl_parse.c
unezQuake sends `say_team` messages with "#inlay#" which is incompatible with the limited `filter` system of ezQuake. Ignore these messages like we ignore Qizmo messages.
> IGNORE: Automatically ignore unezQuake inlay messages

- vid_sdl2.c
This is the only way to work around this hardcoded limitation on MacOS.
Other cvars have no effect and MacOS offers no GL driver options.
> Vsync fix for MacOS

- cl_parse.c
- help_variables.json
- hud_teaminfo.c
- sbar.c
- screen.h
- utils.c
- utils.h
- Implemented scr_shownick_show_ammo to display ammo in /shownick 1
- can also use %k or %K in format string to customize ammo display
- lots of teaminfo stuff: respawn times and dead players while playing ca/wipeout
- Scoreboard kills/deaths reset between rounds in wipeout
- Scoreboard replaces server time with respawn time during wipeout
- Scoreboard dims dead players in ca/wipeout
> Updates to scoreboard, shownick and teaminfo

- gl_framebuffer.c
- help_variables.json
- menu_options.c
- rulesets.c
- rulesets.h
Allow `/gl_outline` in smackdown ruleset, just like `/r_fx_geometry`.
Disallow both in qcon ruleset.
2 new entry in the Options for these two outline settings
> Allow gl_outline in smackdown

- snd_mem.c
SOUND: when loading an external ambient sound (eg water1.wav), in S_ParseCueMark where it calls BuffLittleLong, it always returns the size as 0, causing it to loop forever
> SOUND: when loading an external ambient sound a lockup occurs

- src/r_brushmodel_load.c
This is a common annoyance when TrenchBroom inserts a __TB_Empty texture due to some action when mapping. The result is that the size check later on causes a division by zero which crashes ezQuake without giving any actionable feedback to the user.
> MINOR: Warn on empty textures rather than break.

- help_variables.json
Acknowledge gl_textureless can have varying results depending on mip level (whether that was intentional or not all along, I can not say).
> help: tweaked gl_textureless description

- src/in_sdl2.c
- src/vid_sdl2.c
… it enabled, toggling joystick cvar to 1 initializes joystick device(s)
> INPUT: don't initialize joystick/perform any logic unless cvar has been set, other input initialization fixes

- build-linux.sh
Added automated build script functionality for the [Void Linux](https://voidlinux.org) distribution.
Here is the build log from the tested build I made in a fresh installation chroot: [ezquake-build.log](https://github.com/QW-Group/ezquake-source/files/10434229/ezquake-build.log)
> Void linux build script support

- help_variables.json
- src/cl_main.c
- src/vid_sdl2.c
Adds the command cl_maxfps_menu, defaults to using the refresh rate
still caps at 30 when minimised
> Add cl_maxfps_menu

- help_variables.json
- misc/cfg/gfx_gl_eyecandy.cfg
- misc/cfg/gfx_gl_faithful.cfg
- misc/cfg/gfx_gl_fast.cfg
- misc/cfg/gfx_gl_higheyecandy.cfg
- src/cl_view.c
when enabled cshifts are just happening twice
> CVAR - disable gl_hwblend by default

- src/glsl/draw_world.vertex.glsl
Same fix as in 8a3dc977, but for modern renderer.
For #629
> SKYBOX: Rotate 90 degrees to align with other engines

- src/r_brushmodel_load.c
This fixes the issue with caustics popping up here and there around fence textures.
> BSP: Mark only liquids as underwater.

- src/r_brushmodel_load.c
This makes rctf3_b2 load correctly. The sanity check is easily triggered by adding a skip texture to a func_wall. The other issue is a bit more tricky to reproduce from zero as it depends on what geometry the map compiler decides to spit out, but is what has been discussed on discord the past week or two.
> BSP: Sane sanity check and unsigned surfaces.

- src/in_sdl2.c
- src/vid_sdl2.c
At the original code location the `in_raw` cvar looks like this:
```
(lldb) p in_raw
(cvar_t) $0 = {
name = 0x00000001001dc3e0 "in_raw"
string = 0x00000001001ba16c "1"
flags = 4097
OnChange = 0x0000000100140d1c (ezquake-darwin-arm`in_raw_callback at vid_sdl2.c:273)
value = 0
maxrulesetvalue = 0
minrulesetvalue = 0
defaultvalue = 0x0000000000000000
latchedString = 0x0000000000000000
autoString = 0x0000000000000000
integer = 0
color = ""
modified = false
teamplay = false
group = NULL
next_in_group = NULL
hash_next = NULL
next = NULL
}
```
Which will result in the init code not to be run, but reporting it was successfull.
> INPUT: move macOS in_raw init to a point where in_raw cvar is actually registered

- misc/install/create_osx_bundle.sh
- misc/install/fixbundle.sh
Due to the source files being moved to a subdirectory the script failed to use a correct version when creating the bundle.
The ad-hoc signing could also be done a bit simpler..
> INSTALL: fix versioning for macOS bundle; simplify ad-hoc signing

- src/skin.c
previously the player model was affected by `gl_texturemode` only if `gl_playermip` was not 0, so if you wanted to use the `GL_NEAREST` filter you had to sacrifice some quality (fix #687)
the issue with scaling is visible below
> Fix player skin texture scaling and filtering

- help_variables.json
- src/gl_state.c
- src/r_rmain.c
[this commit](https://github.com/QW-Group/ezquake-source/commit/155e9d731d419701c1c813b3d5ddef78abedb0ec) broke the z-fighting fix by making the units offset negative to prevent buttons being pushed into walls. On my machine it seems that negative offsets are no different than 0, however a negative factor can offset a brush in the opposing direction. I made the factor customizable (`gl_brush_polygonoffset_factor`, range -1 to 1), so players are free to choose which way the brushes are offset.
tested in the same situation as #747 as well as on a [custom map](https://cdn.discordapp.com/attachments/672796268585680906/1103663973045391360/zfixtest.bsp) with doors like this facing all 4 directions
> fix z-fighting 

- src/cl_screen.c
- src/hud_centerprint.c
fix #675 and the `HUD_ON_FINALE` `HUD_ON_INTERMISSION` and `HUD_ON_SCORES` flags
> fix centerprint not appearing during finales (#675)

- help_variables.json
- src/cl_screen.c
- src/hud.c
- src/hud.h
- src/hud_centerprint.c
- src/hud_clock.c
adds https://github.com/QW-Group/ezquake-source/issues/772 and functionality for `HUD_NO_DRAW` 
<br>
<br>
in-game:
- added a new hud element, scoreclock
- it is only displayed when the scoreboard is visible (either at the end of the game or when using `+showscores`/`+showteamscores`)
- `hud_scoreclock_format` cvar controls the format of the clock according to [this](https://www.man7.org/linux/man-pages/man3/strftime.3.html)
<br>
in-code:  
- elements with the `HUD_NO_DRAW` flag set don't draw by default (e.g. an element with `flags = HUD_NO_DRAW | HUD_ON_INTERMISSION` will ONLY draw during the intermission)
> date/time hud element for the scoreboard 

- src/cl_main.c
- src/cl_parse.c
- src/sv_user.c
sv_downloadchunksperframe is 15 now, could be set up to 30.
cl_chunksperframe is 30 now, server could limit it by sv_downloadchunksperframe.
theoretical download speed is about 1024 * 30 * 77, 1024 is chunk size in bytes, 30 is chunks per frame, and 77 is frames per second.
> DOWNLOAD: bump download speed for client and server

- src/bspfile.h
- src/gl_model.h
- src/glm_brushmodel.c
- src/glsl/lighting.compute.glsl
- src/glsl/lighting_copy.compute.glsl
- src/r_brushmodel_load.c
- src/r_lightmaps.c
- src/r_lightmaps_internal.h
This BSPX blob allows mappers to decouple lightmaps from textures so that a map can have higher lightmap resolution without scaling textures, something that otherwise risks introducing aliasing artifacts. Another quirk with texture scaling and vanilla lightmaps is that a texture with 0.5 scale next to one with 1.0 scale causes a visual glitch as the lightmap for the two surfaces have differing resolution.
The feature has been supported by ericw light compiler since end of 2022, and is enabled by setting `_world_units_per_luxel` to an integer value. A setting of `16` is close to vanilla resolution, and a lower value increases the lightmap resolution to the cost of increased bsp size. To reduce size the redundant vanilla lightmaps can be omitted with the `-novanilla` flag to the light …
> LIGHTMAPS: Support for DECOUPLEDLM. 

- misc/vstudio/txt2c/txt2c.vcxproj
I found the x64 debug target for subproject txt2c was the only target still using VS 2019 Platform tools (v142) instead of v143.
Didn't have 142 anymore and couldn't run that debug build... until now.
> BUILD: move txt2c x64 debug target to v143 tools like the others

- src/hud_gamesummary.c
The item counts are centered horizontally for each item icon - pretty much only with default values of hud_gamesummary_scale and hud_gamesummary_ratio. Playing with those will get the text off-center in various ways.
Switched to the existing function for drawing horizontally aligned strings to fix this.
> HUD: gamesummary centers its text regardless of scale/ratio

- src/cmd.c
- src/keys.c
fixed bindedit crashing when used with an unbound key
after using bindedit or aliasedit the cursor now moves to the beginning of the bind/alias value
some additional validity checks in aliasedit
> fixing and tweaking bindedit and aliasedit

- src/glm_rmain.c
- src/glsl/fx_world_geometry.fragment.glsl
turns out amd drivers and nvidia drivers have different float precision so on nvidia you cant compare vectors with `!=` :P
> fixing the horrendous nvidia bug with outlines

- src/fmod.c
fix checksum and set lastid.
With the previous changes in https://github.com/QW-Group/ezquake-source/pull/790 f_modified still reported airbut1.wav. I had two mistakes. I used the checksum of the original airbut1.wav instead of the rerelease. I also did not set lastid.
This time I was able to actually test and f_modified passes on dm2 and e1m2.
> rerelease airbut1.wav f_modified

- src/r_brushmodel_load.c
- src/r_texture.h
- src/r_texture_cvars.c
Aligns the various uglification settings to how gl_textureless deal with fence textures to avoid putting players with gl_miptexlevel > 0, gl_picmip > 0, gl_max_size < 8192 at a competitive disadvantage by keeping fence textures verbatim. Future improvements could be to actually average or pixelate the textures, while keeping the fence alpha intact, but this fixes the immeadiate issue.
Mostly fixes #789, no competitive penalty for the non-normal examples.
> TEXTURES: Fix competitive issues with fence textures.

- src/vid_sdl2.c
This is the default on Linux, and incidentally used to be the default on Windows as well, until vcpkg got introduced which brought a modern SDL version with support for keyboard grabbing.
Fixes #830
> SDL: Default to no keyboard grab on Windows.

- src/glm_brushmodel.c
This caused entities with fence textures to not render. Most likely a copy-paste error from glc as alphachain is otherwise not part of the modern renderer.
Fixes #757
> GFX: Fix fence textures on func.

- .github/workflows/build-targets.yml
- .github/workflows/scripts/homebrew.sh
More details in GitHub documentation:
https://github.com/actions/upload-artifact#maintaining-file-permissions-and-case-sensitive-files
> CI: Double-zip macOS app to keep executable bit.

- src/glm_aliasmodel.c
> [23:53]NinJaA: BUG: gl_outline_use_player_color 1; setting got reseted after vid_restart; i need to manually filp the value from 1->0->1 to get the effect back. tested on ubuntu linux nvidia 535 @ e8ed7a50
> fix outline cvars resetting on vid_restart

- help_variables.json
- src/central.c
- src/host.c
- src/menu_ingame.c
- src/version.c
- src/version.h
A first attempt at version notification. Will show a version outdated message above the in-game menu, which is probably one of the most seen views that doesn't obscure gameplay. Can be extended later on to interact with /version and /f_version.
Fixes #827
> UI: Add notice on outdated client.

- .github/workflows/build-targets.yml
Limiting CI to only upstream project requires contributors to carry their own configuration for CI up until creating a PR, at which point that commit has to be dropped. As there's no drawback to always building, better just enable it everywhere.
> CI: Run CI for downstream projects.

- help_commands.json
- help_macros.json
- help_variables.json
- src/cl_view.c
- Refreshed alphabetical sorting of sections and keys for easier merging over time, keeping maintainers happy.
- The JSON generator is apparently case sensitive -> made HUD262 command descriptions lowercase so it doesn't introduce duplicates.
- Updated defaults in JSON from code: cl_chunksperframe 5 -> 30
cl_demoplay_flash gets its 0.33 back
joy* stuff defaults were missing
r_fx_fog_density 0.002 -> 0.125
scr_cursor_iconoffset_x 10 -> 0
scr_teaminfo_show_countdown 0 -> 1
vid_grab_keyboard 1->0
vid_win_borderless did not mention its default value
- System-generated placeholders for dateiso, fs_savegame_home, vid_reload, vid_reload_auto (to be described)
- Updated some default cvar values according to actual behaviour: v_dlightcolor, v_dlightcshift, cl_bonusflash are actually used as …
> HELP: updates from JSON generator and assorted cleanups

- .github/workflows/build-and-deploy-release.yml
- .github/workflows/build-and-deploy-snapshots.yml
- .github/workflows/build-targets.yml
PIPELINE: linux - use docker to generate appimage so we can choose the distro/version, this is primarily so we can use a newer version of libsdl2 in which mice above 1khz work properly
> Pipeline use docker for linux builds

- misc/appimage/appimage-manual_creation.sh
if register_qwurl_protocol is run while using an appimage, the path/executable name is incorrect as it's set to temporary directory/executable created by running the appimage.
> BUILD: appimage - fix path to appimage

- misc/appimage/appimage-manual_creation.sh
the uri should be passed in as first argument regardless but it would appear under some circumstances this doesn't happen
> BUILD: appimage - append +qwurl %u to exec entry in desktop file

- src/hud_ammo.c
- src/hud_common.c
adds style 3 to most numeric hud elements (health, ammo, armor, gameclock, ...) which makes the text small gold letters from the console charset
> improvements to some numeric hud elements

- src/pr_cmds.c
- src/pr_exec.c
- src/sv_init.c
- src/sv_main.c
- src/sys_posix.c
see #826
- progs errors do not crash ezquake anymore, instead the server is stopped and errors are displayed in the console
- the linux version now shows a message box instead of straight up exiting
ideally some more errors to change would be suggested
> Improve error handling

- src/vx_tracker.c
Allow a prefix to be prepended to r_tracker messages that are printed in the console.
> VX_TRACKER: Add r_tracker_string_inconsole_prefix

- src/EX_browser.c
It's annoying that you have to esc out before using the arrow keys / mouse wheel when you browse servers to check who is online. This PR allows you to keep the serverinfo window open when scrolling up or down. Note that the old behavior for scrolling up / down in the individual serverinfo tabs is preserved with ctrl+arrow etc. 
We do lose the old ctrl+arrow behavior where you could go to the end of the server list by doing ctrl+downarrow, but I think it's such a rare use case that it's fine.
> Allow server browser scrolling when serverinfo open

- src/vfs_zip.c
Most of the uses had already been removed, but remained in the case of a seek. As cmodel now uses seeks during checksum, this uncovered the last use case.
As iscompressed wasn't set, the vfsz->defer remained NULL, and thus reading of pk3 content after a seek failed.
The origin of this file is FTE, ideally a newer version is imported but the rest of the FTE VFS guts has evolved since last import.
fixes #885
> FS: Remove last traces of iscompressed in vfs_zip.

- help_variables.json
- src/vx_tracker.c
This cvar fixes the color of tracker messages so that both names are colored similarly.
> TRACKER: r_tracker_colorfix colors both names in frag line

- src/utils.c
The `RGBToString` function is intended to serve as the inverse of `TrackerStringToRGB_W`, which is responsible for translating `[0-9]` to `[0-255]`.
However, the previous version of `RGBToString` did not function correctly. For instance, the value `255` was inaccurately converted to `9`, which is incorrect (it should be `15`).
This patch aims to address the issue and correctly convert the bytes to their downscaled hex character representation."
> Fix RGBToString conversion

- src/sv_ccmds.c
- src/sv_demo.c
A server can execute commands on the client via stufftext. Therefore, a malicious server can perform evil operations. To limit the attack vector, the following commands have been disabled in the client:
- chmod
- localcommand
- ls
- nslookup
- rm
- rmdir
- script
> Don't compile dangerous commands in client

- help_variables.json
- src/hud_frags.c
hud_frags_style 3 - shows no indicator around self frags
hud_frags_vertical 2 - splits columns evenly based on number of players without having to manually change row count
Also: frags element has been extended to display CA/Wipeout game state.
> Additions to hud_frags element

- .github/workflows/scripts/homebrew.sh
Just homebrew noise, nothing related to the actual build.
> CI: Workaround for build-dep conflicts on macOS.

- Makefile
- src/glm_aliasmodel.c
- src/in_sdl2.c
- src/r_brushmodel_load.c
The wiki specifies that C89 is the target standard. In reality the codebase adheres to GNU89. When actually enforcing this the behavior of MinGW cross-compilation changes, which allows JSON_INTEGER_FORMAT to work as intended.
Later standards automatically enable __USE_MINGW_ANSI_STDIO=1 in MinGW which is the cause of the jansson breakage.
It seems to be fairly common to combine __STDC_FORMAT_MACROS=1 and __USE_MINGW_ANSI_STDIO=0 in projects that disable it.
> STYLE: Fix some c89 violations.

- src/vid_sdl2.c
This was an accidental casualty introduced in 5a8e4580d769fb45eaef89de0b46e4dbed4010ae.
> CVAR: Revert typo introduced when fixing macOS gamma.

- help_variables.json
- src/r_lightmaps.c
- src/r_rmain.c
This is a temporary workaround primarily targeted at macOS arm64 on which the GPU has a high risk of clipping nearby triangles if zero sized triangles are fed to the GPU. At best this bug introduces rendering glitches from looking into the void, at worst it allows the player to see enemies behind walls in matches.
The workaround is force-enabled on macOS arm64. But there have been mysterious rendering issues with missing surfaces in the past, so other targets may opt-in to enable it and see if it helps.
> RENDERER: Add option to filter out collinear vertices.

- .gitignore
As recommended in `BUILD.md`, the build directory should be created when building from source, so it should probably be added to `.gitignore` as well.
> Ignore the /build directory

- src/cl_ents.c
- src/cl_main.c
- src/cl_parse.c
- src/client.h
- src/g_public.h
- src/pr2_cmds.c
- src/pr_cmds.c
- src/pr_edict.c
- src/progs.h
- src/r_aliasmodel.c
- src/render.h
- src/sv_ents.c
- src/sv_main.c
- src/sv_user.c
- src/vm_interpreted.c
FTE_PEXT_TRANS was broken when implemented long ago. This finishes the implementation, and also adds FTE_PEXT_COLOURMOD which was declared, but only implemented in renderer. The latter is a convenient extension field for mappers to use when dealing with alpha brushes later on. For example using the same glass texture with alpha, but tint it via colormod field.
Broken clients (all ezQ versions) will be demoted to opaque entities based on revision.
The renderer is only wired up to use the colourmod and alpha values, but is otherwise unchanged. Even if it has sorting already to blend transparent faces in a somewhat ok order, there are a number of bugs that may for example skip drawing entities behind a transparent entity. This will be dealt with in a later PR that also adds alpha brush …
> Support FTE_PEXT_TRANS and FTE_PEXT_COLOURMOD.

- CMakeLists.txt
This causes the executable to linked with libGL etc instead of libOpenGL etc. This only changes the behavior on *nix sytems.
> CMAKE: Switch OpenGL detection to legacy.

- src/cl_ents.c
Same entity variable is reused during iteration. If not reset when unmodified, other entities will be tainted.
> CLIENT: Reset RF_FORCECOLOURMOD if unmodified.

- src/cmd.c
- src/gl_model.h
- src/pr2_exec.c
- src/pr_edict.c
- src/r_aliasmodel_md3.c
- src/r_brushmodel_warpsurfaces.c
- src/r_lightmaps.c
- src/r_refrag.c
- src/sv_save.c
- src/vm.c
- src/vm_interpreted.c
- src/wad.c
- src/zone.c
- src/zone.h
Exposes hunk_print to the client, names previousyl unnamed allocations and drops dead code to save memory.
> MEMORY: Hunk ergonomics.

- help_commands.json
- help_variables.json
- src/gl_program.c
- src/glc_sky.c
- src/glm_local.h
- src/glm_misc.c
- src/glm_rsurf.c
- src/glsl/common.glsl
- src/glsl/draw_world.fragment.glsl
- src/glsl/glc/glc_sky.fragment.glsl
- src/r_brushmodel_sky.c
- src/r_brushmodel_sky.h
- src/r_program.h
- src/r_rmain.c
Feature available in the SP community. Ported mostly verbatim from the IronWail engine. Partial cubemap alpha which gets blended with itself to create the illusion of a moving sky. Quite hypnotizing.
To simplify tuning of the skybox the following commands are included in the port:
* /skywind
* /skywind_save
* /skywind_load
* /skywind_lookdir
* /skywind_rotate
If a config file named $skyboxname_wind.cfg in the same directory as the skybox is found, it's automatically loaded and configures the sky.
Implemented for both modern and classic renderers.
> RENDERER: Add support for skywind.

- help_variables.json
- src/cl_cmd.c
- src/cl_parse.c
- src/cmd.c
This PR addresses the RCE issue that I discovered earlier this year. It consists of three new cvars:
- `cl_remote_capabilities`, controls which commands and variables the server is allowed to execute or set on the client. The default values used here should be compatible with KTX use.
- `cl_allow_downloads`, allows the user to control which file extensions a client/server can download/upload from/to the server/client.
- `cl_allow_uploads`, toggles whether or not the upload function is enabled. This prevents the server from downloading files from the client's computer.
> Add remote capabilities validation

- src/glm_rsurf.c
The drawcall offset was incorrectly double-offset by both calculating polygonOffset_offset in GLM_DrawWorldModelBatch and then for each iteration further offsetting that base offset by drawcall->polygonOffsetSplit via loop variable.
> MODERN: Unbreak and enable draw call batching.

- src/cl_cmd.c
- src/cmd.c
- src/cmd.h
This ensures that no file a server uploads to your client can be executed.
> Prevent downloadable files from being executed

- src/sbar.c
Previously, when using `+showscores`, it displayed map name, kills, skill and how many secrets that were found, this information isn't very valuable during a deathmatch game, so instead I changed it to just display the system clock.
> Display the clock in +showscores during deathmatch gameplay

- help_variables.json
- src/cmd.c
When using wreg and spectating on a KTX server, {+,-}attack commands are issued when firing.
See: https://github.com/QW-Group/ktx/blob/master/src/commands.c#L7246-L7263
> Allow server to stufftext {+,-}attack

- src/cl_parse.c
Since the server doesn't include overtime data, we can't rely on the STAT_MATCHSTARTTIME data when using a game clock that counts down. Instead, we'll have to wait for a "[X] minutes remaining" message to sync the game clock. Without this, during overtime, the clock will start counting up instead of down.
> Disable STAT_MATCHSTARTTIME sync if gameclock counts down

- help_variables.json
- gl_coronas: hint towards gl_particle_* effects
- gl_coronas_tele: mention teleports (as should be, it's in the cvar name) and simplify
- gl_lightning: hint at coronas controlling the big fat glow, clarified ruleset impact
> HELP: clarify gl_coronas*/gl_lightning

- src/hash.c
The Hash_Remove and Hash_RemoveKey functions incorrectly freed the wrong node when unlinking an entry in the linked list, causing a crash.
This issue went unnoticed until now because the functions were previously unused.
> HASH: Fix incorrect node removal in Hash_Remove and Hash_RemoveKey

- CMakeLists.txt
- src/cl_ents.c
- src/glm_aliasmodel.c
- src/glm_local.h
- src/glm_rsurf.c
- src/glsl/common.glsl
- src/glsl/draw_world.fragment.glsl
- src/glsl/draw_world.vertex.glsl
- src/r_states.c
> MODERN: Add support for alpha brushes.

- src/version.c
Once per lifetime leak, but headers should ofc be freed.
> UI: Fix memleak in version check.

- src/console.c
snprintf implementation may decide to write at the end of the specified buffer length for security reasons which will produce a crash even if the conditions happen to be within bounds.
> CONSOLE: Fix buffer overflow.

- help_variables.json
- src/cmd.c
The following aliases has been added:
- on_admin
- on_connect
- on_connect_ctf
- on_connect_ffa
- on_matchend
- on_matchstart
- on_observe
- on_observe_ctf
- on_observe_ffa
- on_spec_matchend
- on_spec_matchstart
- on_unadmin
> Update defaults for cl_remote_capabilities

- src/cl_screen.c
3.0 added more math to mostly classic, GLQWCL CalcFov to try and derive FOV from a reference 4:3 ratio.
This accomodated everything above 4:3, which was becoming the norm at the time.
3.0.1 also added a letterbox option which somewhat "maintains" FOV for `viewsize < 100` - for ratios 4:3+.
Viewport size is not always strictly proportional to the vid size, due to the varying margins that are added - i.e, the aspect ratios do not always match.
However, classic GLQWCL CalcFov always worked on viewport size, whether it was the screen size or not - so there was never a problem.
3.0.1+ passes the viewport size *and* the vid size and takes both into account for 4:3+, but still only works from vid size under 4:3.
Result: in some rare combinations at those narrow ratios, the viewport and screen …
> FOV: fix rare CalcFov+viewsize glitches

- src/glsl/draw_aliasmodel.fragment.glsl
- src/glsl/draw_world.fragment.glsl
Fixes issue where fog caused alpha brushes to look more transparent than intended.
> MODERN: Apply alpha after fog.

- src/gl_model.h
- src/r_brushmodel_load.c
- src/r_lighting.h
- src/r_lightmaps.c
- src/r_rlight.c
This format was added to ericw-tools spring 2024. Initial implementation does not expose it's full range potential, but it loads, and works, which gives mappers the option to target this format instead of the old rgb8 format.
Ported from QuakeSpasm-Spiked, also implemented in FTE.
> LIGHTMAPS: Support for loading e5bgr9 lightmaps.

- src/cl_ents.c
Clear visents that were in use, or fallback to all. Should be revisited at a later point in time. At least normally smaller memset than there used to be.
> ENTS: Partially revert "Skip clearing visents list".

- help_variables.json
- src/sbar.c
Default view of `+showscores`, without any of the new settings applied:
Default view of `+showscores` where `scr_scoreboard_highlightself` is set to `0`:
`+showscores` where `scr_scoreboard_classic` is set to `1`
> Add scoreboard settings

- help_variables.json
- src/sbar.c
Allow toggling the visibility of the clock at the bottom of the screen when using +showscores or +showteamscores.
`scr_scoreboard_showclock 0`:
`scr_scoreboard_showclock 1`:
> Add scr_scoreboard_showclock

- help_variables.json
- src/cl_cmd.c
- src/sbar.c
- src/teamplay.c
There was a version of qwcl where you could use black and orange colors, but I haven't been able to figure out which version included them or when they were removed.
The current color selection algorithm works like `x * 16 + 8`, where `x` is a row in the Quake palette (as seen here: https://quakewiki.org/wiki/Quake_palette).
So, `color 0` is the same as `0 * 16 + 8`, which maps perfectly to the white color in the palette. The same goes for the other colors between 0 and 13.
I'm uncertain about the exact shade of orange that was possible to use, but my guess is that it was `14 * 16 + 8 == 232`.
`color 14`:
`color 15`:
Old screenshot that demonstrates the black color:
https://www.quakeworld.nu/w/images/4/4c/RFVSSC1.JPG
> Allow orange, bright red and black colors

- src/glsl/draw_world.fragment.glsl
- src/glsl/draw_world.vertex.glsl
- src/glsl/glc/glc_world_drawflat.fragment.glsl
- src/glsl/glc/glc_world_drawflat.vertex.glsl
- src/glsl/glc/glc_world_textured.fragment.glsl
- src/glsl/glc/glc_world_textured.vertex.glsl
Prevents bright artifacts along BSP splits in dark areas when using MSAA.
> RENDERER: enable centroid sampling for world geometry

- src/rulesets.c
- src/rulesets.h
- src/snd_main.c
The `play` command was previously restricted only in the `qcon` ruleset. This PR extends the restriction to `smackdown` and `smackdrive` as well.
Additionally, it includes a minor refactor to better align the function with other restriction functions - specifically, ensuring that `play` is only be prevented during an ongoing game and allowed in prewar.
Thanks to gnoffa for pointing out that the `play` command should be restricted!
> Restrict play in ruleset smack{down,drive}

- help_variables.json
- src/hud_gamesummary.c
- src/sbar.c
The new options allow you to display the current map name when +showscores / +showteamscores are toggled.
Example of the three display formats:
- Full name: The Abandoned Base (dm3)
- Level name: The Abandoned Base
- Map name: dm3
Example screenshots:
> Add scr_scoreboard_showmapname and hud_scoremapname variables

- help_variables.json
- src/sbar.c
Set scr_scoreboard_classic to 2 for a qwcl 1.50/1.55-style scoreboard, enhancing the classic look.
scr_scoreboard_classic 0
scr_scoreboard_classic 1
scr_scoreboard_classic 2
> Add additional scr_scoreboard_classic customization

- help_variables.json
- src/qtv.c
- src/qtv.h
- src/sbar.c
By setting scr_scoreboard_showqtvusers to 1, you can display the currently connected QTV users in the scoreboard.
This feature requires an MVDSV server capable of relaying QTV events to regular clients.
New variables:
- scr_scoreboard_showqtvusers (default: 0)
- scr_scoreboard_qtv_name (default: qtv)
- qtv_event_msglevel (default: 1)
0: Disables QTV event messages
1: Enables QTV event messages
2: Hides QTV event messages when a match has started
Screenshot:
Depends on: https://github.com/QW-Group/mvdsv/pull/168
> Add support for displaying QTV users in the scoreboard

- src/net.c
This fixes the issue @BLooD-DoG reported earlier today (also previously mentioned by @sopparus, but I couldn't reproduce it at the time), where the client would crash.
The crash could be reproduced by:
1. Enabling port ping probing
2. Connecting to a server
3. Disconnecting from the server
4. Connecting to a server with an invalid hostname
5. Crash
> Initialize results to NULL so it's always safe to free

- help_variables.json
- src/cl_parse.c
- src/ignore.c
Setting ignore_no_weapon to 1 will suppress the "no weapon." message emitted by KTX. Similarly, ignore_not_enough_ammo will suppress the "not enough ammo." message.
> Add ignore_{no_weapon,not_enough_ammo}

- src/settings.h
- src/settings_page.c
14/15/16 could be displayed but not selected and were not named correctly.
Added Orange, Bright Red, Black and resized enum to fit.
> MENU: add Slime's revived new-old player skin colors

- src/help.c
When a cvar is highlighted in Advanced mode, the info box now also shows the default value.
Gathered from JSON help like the rest of the fields.
> MENU: Show defaults in cvar infobox in Advanced menu mode
